
require("The Vanguard.carzyconfig.set")
require("The Vanguard.carzyconfig.lspconfig")
require("The Vanguard.carzyconfig.treesitter")
require("The Vanguard.carzyconfig.tabby")
require("The Vanguard.carzyconfig.harpoon")
require("The Vanguard.carzyconfig.incsearch")
require("The Vanguard.carzyconfig.delimit")
require'colorizer'.setup()
require("The Vanguard.carzyconfig.autopairs")
-- require("The Vanguard.carzyconfig.feline")
require("The Vanguard.carzyconfig.tabby1")
