require("The Vanguard.carzyconfig.remap")
require("The Vanguard.lazy")
require("The Vanguard.carzyconfig")
-- require("luasnip.loaders.from_vscode").lazy_load()
-- require("luasnip.loaders.from_snipmate").lazy_load()
--require("The Vanguard.feline")
--require("The Vanguard.tabby")
-- require("The Vanguard.carzyconfig.lspconfig")
-- require("The Vanguard.carzyconfig.treesitter")
-- require("The Vanguard.carzyconfig.tabby")
-- require("The Vanguard.carzyconfig.harpoon")
-- require("The Vanguard.carzyconfig.incsearch")
-- require("The Vanguard.carzyconfig.delimit")
-- require'colorizer'.setup()
-- require("The Vanguard.carzyconfig.autopairs")
-- print("ok done")
