require("The Vanguard.remap")
require("The Vanguard.lazy")
require("The Vanguard.set")
require("The Vanguard.lspconfig")
require("The Vanguard.treesitter")
require("The Vanguard.tabby")
require("The Vanguard.harpoon")
print("ok done")
